# ðŸš¨ DEFAULT CONFIG ðŸš¨
name = "webhook"
compatibility_date = "2024-04-29"
main = "./index.ts"
node_compat = true

[placement]
mode = "smart"

[define]
_APP_ENV = "'development'"



# =====================================
# =====================================
# ðŸš¨ PRODUCTION CONFIG ðŸš¨
# =====================================
# =====================================
[env.production]
route = "webhook.communityos.io/*"

[env.production.placement]
mode = "smart"

[env.production.define]
_APP_ENV = "'production'"






# =====================================
# =====================================
# ðŸš¨ STAGING CONFIG ðŸš¨
# =====================================
# =====================================
[env.staging]
route = "webhook.jsconf.dev/*"

[env.staging.placement]
mode = "smart"

[env.staging.define]
_APP_ENV = "'staging'"

