# ðŸš¨ DEFAULT CONFIG ðŸš¨
name = "auth_tokens"
compatibility_date = "2023-06-06"
main = "./index.ts"

[placement]
mode = "smart"

[define]
_APP_ENV = "'development'"





# =====================================
# =====================================
# ðŸš¨ PRODUCTION CONFIG ðŸš¨
# =====================================
# =====================================
[env.production]
route = "auth-tokens.jschile.org/*"

[env.production.placement]
mode = "smart"

[env.production.define]
_APP_ENV = "'production'"






# =====================================
# =====================================
# ðŸš¨ STAGING CONFIG ðŸš¨
# =====================================
# =====================================
[env.staging]
route = "auth-tokens.jsconf.dev/*"

[env.staging.placement]
mode = "smart"

[env.staging.define]
_APP_ENV = "'staging'"

