name: Lint and Typecheck

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    # Mover clone/setup/cache_restore/cache_save a un composite action ğŸ™
    steps:
      - name: â³ Cloning repo
        uses: actions/checkout@v3

      - name: â¬¢ Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: ğŸ“¦ Download Cached Package Dependencies
        uses: actions/cache/restore@v3
        env:
          cache-name: NPM
        with:
          path: ~/.npm
          key: CACHE-${{ env.cache-name }}

      - name: ğŸ“¦ Download Cached Eslint output
        uses: actions/cache/restore@v3
        env:
          cache-name: ESLINT
        with:
          path: .eslintcache
          key: CACHE-${{ env.cache-name }}

      - name: ğŸ“¦ Download Cached Typescript output
        uses: actions/cache/restore@v3
        env:
          cache-name: TYPESCRIPT
        with:
          path: tsconfig.tsbuildinfo
          key: CACHE-${{ env.cache-name }}

      - name: ğŸ“¥ Download deps
        run: npm ci --prefer-offline --no-audit --cache ~/.npm

      - name: Run Linter
        run: npm run lint

      - name: Run Typecheck
        run: npm run typecheck

      - name: ğŸ“¦ Upload Cached Package Dependencies
        uses: actions/cache/save@v3
        # if: github.ref == 'refs/heads/main'
        env:
          cache-name: NPM
        with:
          path: ~/.npm
          key: CACHE-${{ env.cache-name }}

      - name: ğŸ“¦ Download Cached Eslint output
        uses: actions/cache/save@v3
        # if: github.ref == 'refs/heads/main'
        env:
          cache-name: ESLINT
        with:
          path: .eslintcache
          key: CACHE-${{ env.cache-name }}

      - name: ğŸ“¦ Download Cached Typescript output
        uses: actions/cache/save@v3
        # if: github.ref == 'refs/heads/main'
        env:
          cache-name: TYPESCRIPT
        with:
          path: tsconfig.tsbuildinfo
          key: CACHE-${{ env.cache-name }}
